# Site settings
title: RAYCHAIN
email: master@raychain.cc
url: https://raychain.co
description: "一链迷众生，一链觉则佛"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: RAYCHAIN.CC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, stack-overflow, bitbucket, etc.)
social:
  - title: weibo
    url: 
  - title: wechat
    url:
  - title: github
    url: 

# Build settings
markdown: kramdown
permalink: pretty
